name: Deploy TemplateUploadLambda

on:
  push:
    paths:
      - 'TemplateUploadLambda/**'
      - '.github/workflows/deploy-template-upload-lambda.yml'
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Restore dependencies
        run: dotnet restore TemplateUploadLambda/TemplateUploadLambda.csproj

      - name: Build
        run: dotnet build TemplateUploadLambda/TemplateUploadLambda.csproj --configuration Release --no-restore

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 # Change as needed
        run: |
          dotnet lambda deploy-function \
            --project-location TemplateUploadLambda \
            --function-name YourTemplateUploadLambdaName